set-option -g prefix C-a
unbind-key C-b
bind-key C-a send-prefix

unbind %
unbind '"'
bind r split-window -h
bind f split-window -v

set -g mouse on

bind-key -T copy-mode Enter send-keys -X copy-pipe-and-cancel "wl-copy"
bind-key -T copy-mode MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "wl-copy"